### ISSUE TITLE
Encrypted CRDTs (particularly 2P-sets)

### ISSUE THREAD

**Issue by lvh** [replikativ/replikativ#1]
I'm going to write an encrypted 2P-set, and I'm trying to figure out if it would make sense to add it to replikativ. It's not entirely clear to me yet how much of replikativ right now is in the repo CRDT, but it seems like there are two major problems that would need to be addressed:
1. Authentication: not everyone should be able to subscribe to everyone's txn data, _even_ if that txn data is encrypted. The idea that encrypted data and metadata can be public isn't always true: both can leak important information (e.g. size oracles which can be used to mount compression oracle attacks for encrypted data; ongoing incidents due to unusually churn in metadata) that we know attackers leverage in _today's_ systems.
2. Encryption: it seems like the approach replikativ takes today is to not encrypt metadata, potentially authenticate (see above), and then encrypt transaction data. Barring issues with that (see above), is that correct?

I'm actually interested in when the revocations happen, so I just want a plain 2P-set, not an optimized set that kills tombstones later. Updates passing locally and then potentially being passed to other clients without the server knowing sounds great though :)

Let me know if a more detailed description of what I'm thinking of right now would help.

**Comment by whilo** [comment]
This sounds interesting. In general my motivation is to share data as this can help to decentralize the current architecture and unlock the value in data. Nothing can be as bad as losing your private data to some data silo company as is the case atm.

1.+2. My assumption is that encryption is a gradual measure and you get a long way by end-to-end value encryption. What parts of metadata exposure do you see as particularly problematic?  Access patterns on data can reveal some statistics, but you need to expose some information to have a scalable open replication system. At the moment the exposed metadata is only needed for the replication protocol. As an untrusted peer you won't be able to subscribe to private repositories unless you are authenticated for them, but peers inside the trust network will still mirror the data if you are registered as a user on them. Otherwise I don't see a way to replicate without coordination (in a gossip-like network). One could try to verify that you are registered with a peer to limit the trust networks' reach, but in general the information should propagate as quickly as possible and the network should try to converge. If you just propagate to selected peers, which is in the decision of each peer, then the others just won't know and some of your devices (replicas) might get cut permanently.

I am still working on a first release, what is mostly missing is a final update to our prototype https://github.com/kordano/topiq and an update to the documentation. More advanced features like authentication and encryption are on the radar. I have put quite some effort into decoupling the repo CRDT from the replication, so it should be absolutely doable to extend the protocol for another CRDT. You can start by just implementing POpBasedCRDT https://github.com/replikativ/replikativ/blob/master/src/replikativ/protocols.cljc and carry the values in the metadata. We just haven't had time to do it yet. If you have any problems, let me know and I will see what I can do :smile: .

**Comment by lvh** [comment]
> As an untrusted peer you won't be able to subscribe to private repositories unless you are authenticated for them, ...

To be clear, this is in a hypothetical implementation, not something I can find in the repo right now, right?

> ... but peers inside the trust network will still mirror the data if you are registered as a user on them. 

I'm not sure what a "trust network" is in this context.

> What parts of metadata exposure do you see as particularly problematic?

There's a few, but it mostly gets interesting when you combine metadata from multiple sources. I'm trying to build software for security teams facing fairly advanced threat actors (at least right now), so that's a concern. High churn typically notes ongoing incidents; that's useful to know for social engineering and mounting your own attacks. Consider e.g. a case where set entries are capabilities (or just API keys or something); observing the set growing means someone acquired/revoked a capability.

If I assume trust network to mean "mutually authenticated devices replicating to one another", that narrows it down to size (and potential compression) side-channels, which is a lot less worrisome; I can fix that one one level up (size blinding the blobs, for example).

> POpBasedCRDT

I'm guessing the P just stands for Protocol? :)

**Comment by lvh** [comment]
Thanks for your reply! I'll see how much is necessary to implement in replikativ and how much can just be implemented as a layer on top; although I'm a bit concerned that the layer will be too coupled that there's any useful reuse :)

**Comment by lvh** [comment]
Additionally, for purposes of hiding metadata, I'm wondering if PIR (private information retrieval)/OT (oblivious transfer) might be of use, but then there's definitely very little that can be reused.

**Comment by whilo** [comment]
> To be clear, this is in a hypothetical implementation, not something I can find in the repo right now, right?

An implementation was started by @kordano and me a year ago, but never finished: https://github.com/replikativ/replikativ/blob/master/src/replikativ/p2p/auth.cljc 
My idea was to divide the peers in two classes, untrusted peers which need to authenticate to subscribe private repositories and then a general trust network between servers which mirror on user level as much as they like. But this is not set in stone, it is rather motivated by having no central coordination about who might replicate what. I assume that once you allow others to copy your data you should assume that it can spread in arbitrary places, so you either encrypt it or make it public from the beginning.

> If I assume trust network to mean "mutually authenticated devices replicating to one another", that narrows it down to size (and potential compression) side-channels, which is a lot less worrisome; I can fix that one one level up (size blinding the blobs, for example).

Yes, although the network is supposed to replicate in a potentially hostile environment. So some protections against DOS attacks by injecting a lot of dummy writes over CRDTs for example might be necessary. But these issues can better be solved on the way, as at the moment the architecture is really open to adaptation. I would only restrict that once I know more about the scalability and applications. I am at the moment more worried about making it attractive for frontend developers so it actually is used.

> I'm guessing the P just stands for Protocol? :)

You are correct. :)

> Thanks for your reply! I'll see how much is necessary to implement in replikativ and how much can just be implemented as a layer on top; although I'm a bit concerned that the layer will be too coupled that there's any useful reuse :)

I have tried to decouple the parts as much as possible so far. So you have a general pub-sub architecture which connects peers by two bidirectional core.async channels. These channels can be intercepted by "middlewares" in any way needed (somewhat similar to ring, but you can also actively inject communication and everything is edn). The CRDT part is separate and then there are a whole bunch of building blocks which form separate projects now: https://github.com/replikativ/ One important aspect is that it has to work cross-platform to reach the Browser, otherwise you could reuse JVM libraries of course. But this would miss the biggest potential at the network edges of replication.

> Additionally, for purposes of hiding metadata, I'm wondering if PIR (private information retrieval)/OT (oblivious transfer) might be of use, but then there's definitely very little that can be reused. 

If you implement the PIR mechanism against the protocols, then the CRDT implementations can be shared without replication. I try to decouple things and factor them out as far as possible once I have some understanding how they need to be to work nicely together. Do you think about some offline transfer or how would you do it?

**Comment by whilo** [comment]
I have simplified the codebase by the removal of internal identities (i.e. branches for CDVCS). I also have exposed all CRDT related serialization, so you can implement your datatypes in a separate codebase and then extend the three core protocols as needed and supply a constructor for your instances. The p2p networking is also in a [separate project](https://github.com/replikativ/kabel) now. If you have any problems, let me know.

**Comment by lvh** [comment]
Okiedokie :) Started thinking about this on vacation, so significantly more time-constrained now; not sure when/if I'll be able to do something with this.

**Comment by whilo** [comment]
Ok, I will close this for now. Feel free to reopen it or post new issues if you need to.
